// lib/fleet.ts
export interface FleetCar {
  id: string;
  name: string;
  category: "city" | "mpv" | "suv" | "executive" | "premium" | "luxury";
  image: string;
  mobileImage?: string; // Menambahkan properti untuk gambar mobile
  priceType: "lepas-kunci" | "all-in" | "contact";
  manualPrice?: string;
  maticPrice?: string;
  allInPrice?: string;
  driverWithFuelPrice?: string;
  year: number;
  fuel: "Bensin" | "Diesel" | "Hybrid";
  rating: number;
  bookings: number;
  whatsappText: string;
  note?: string;
  passengers: number;
  engine: string;
  transmission: "Manual" | "Matic" | "Manual & Matic";
  features: string[];
}

const fleetData: FleetCar[] = [
  // --- MOBIL LEPAS KUNCI (Manual & Matic) & PAKET SUPIR ---
  {
    id: "brio-2023",
    name: "Honda Brio",
    category: "city",
    image: "/images/cars/brio.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.7,
    bookings: 150,
    whatsappText: "Halo, saya ingin menyewa Honda Brio.",
    passengers: 5,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Sporty Design", "Touchscreen Audio", "Keyless Entry", "ABS"],
  },
  {
    id: "ayla-2023",
    name: "Daihatsu Ayla",
    category: "city",
    image: "/images/cars/ayla.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.5,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Daihatsu Ayla.",
    passengers: 5,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Compact Design", "Audio System"],
  },
  {
    id: "agya-2023",
    name: "Toyota Agya",
    category: "city",
    image: "/images/cars/agya.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.6,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Toyota Agya.",
    passengers: 5,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Stylish Design", "Digital AC"],
  },
  {
    id: "calya-2023",
    name: "Toyota Calya",
    category: "mpv",
    image: "/images/cars/calya.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.6,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Toyota Calya.",
    passengers: 7,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Rear AC", "Spacious Cabin"],
  },
  {
    id: "sigra-2023",
    name: "Daihatsu Sigra",
    category: "mpv",
    image: "/images/cars/sigra.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.5,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Daihatsu Sigra.",
    passengers: 7,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Dual SRS Airbags", "ISOFIX"],
  },
  {
    id: "xpander-2023",
    name: "Mitsubishi Xpander",
    category: "mpv",
    image: "/images/cars/xpander.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.8,
    bookings: 110,
    whatsappText: "Halo, saya ingin menyewa Mitsubishi Xpander.",
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: [
      "Cruise Control",
      "Spacious Cabin",
      "Rear AC",
      "Keyless Operation",
    ],
  },
  {
    id: "xl7-2023",
    name: "Suzuki XL7",
    category: "suv",
    image: "/images/cars/xl7.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.7,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Suzuki XL7.",
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["Sporty Design", "Hill Hold Control"],
  },
  {
    id: "avanza-2023-new",
    name: "Toyota All New Avanza",
    category: "mpv",
    image: "/images/cars/toyota-avanza-all-new.jpg",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.8,
    bookings: 125,
    whatsappText: "Halo, saya ingin menyewa Toyota All New Avanza.",
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: [
      "Air Conditioner",
      "Audio System",
      "Power Windows",
      "Dual SRS Airbags",
    ],
  },
  {
    id: "terios-2023",
    name: "Daihatsu Terios",
    category: "suv",
    image: "/images/cars/terios.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.7,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Daihatsu Terios.",
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["360 Camera", "Keyless Entry"],
  },
  {
    id: "rush-2023",
    name: "Toyota Rush",
    category: "suv",
    image: "/images/cars/rush.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.7,
    bookings: 105,
    whatsappText: "Halo, saya ingin menyewa Toyota Rush.",
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["LED Headlights", "6 SRS Airbags"],
  },
  {
    id: "innova-reborn-2023-new",
    name: "Toyota Innova Reborn",
    category: "mpv",
    image: "/images/cars/innova-reborn.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 550.000",
    maticPrice: "Rp 600.000",
    driverWithFuelPrice: "Rp 900.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.9,
    bookings: 98,
    whatsappText: "Halo, saya ingin menyewa Toyota Innova Reborn.",
    passengers: 7,
    engine: "2400cc",
    transmission: "Manual & Matic",
    features: [
      "Captain Seats",
      "Premium Audio",
      "Climate Control",
      "ABS & EBD",
    ],
  },
  {
    id: "innova-zenix-2023",
    name: "Toyota Innova Zenix",
    category: "mpv",
    image: "/images/cars/innova-zenix.webp",
    priceType: "lepas-kunci",
    manualPrice: "-",
    maticPrice: "Rp 750.000",
    driverWithFuelPrice: "Rp 1.000.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.9,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Toyota Innova Zenix.",
    passengers: 7,
    engine: "2000cc",
    transmission: "Matic",
    features: ["Captain Seats", "Sunroof", "TSS"],
  },
  {
    id: "ertiga-hybrid-2023",
    name: "Suzuki Ertiga Hybrid",
    category: "mpv",
    image: "/images/cars/ertiga-hybrid.webp",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.8,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Suzuki Ertiga Hybrid.",
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["Smart Hybrid", "Cruise Control"],
  },

  // --- MOBIL PAKET ALL-IN ---
  {
    id: "fortuner-2023",
    name: "Toyota Fortuner",
    category: "suv",
    image: "/images/cars/fortuner.webp",
    mobileImage: "/images/cars/toyota-fortuner-mobile.jpg", // Menambahkan gambar mobile
    priceType: "all-in",
    driverWithFuelPrice: "Rp 1.300.000",
    year: 2023,
    fuel: "Bensin",
    rating: 4.9,
    bookings: 76,
    whatsappText: "Halo, saya ingin menyewa Toyota Fortuner.",
    note: "Harga sudah termasuk mobil, supir & BBM.",
    passengers: 7,
    engine: "2800cc",
    transmission: "Matic",
    features: ["Leather Seats", "Sunroof", "360 Camera", "Advanced Safety"],
  },
  {
    id: "pajero-2023",
    name: "Mitsubishi Pajero",
    category: "suv",
    image: "/images/cars/pajero.webp",
    priceType: "all-in",
    driverWithFuelPrice: "Rp 1.500.000",
    year: 2023,
    fuel: "Diesel",
    rating: 4.8,
    bookings: 68,
    whatsappText: "Halo, saya ingin menyewa Mitsubishi Pajero Sport.",
    note: "Harga sudah termasuk mobil, supir & BBM.",
    passengers: 7,
    engine: "2400cc",
    transmission: "Matic",
    features: [
      "Sunroof",
      "Cruise Control",
      "Leather Seats",
      "Hill Descent Control",
    ],
  },
  {
    id: "elf-minibus-2023",
    name: "Isuzu Elf Minibus",
    category: "executive",
    image: "/images/cars/isuzu-elf-minibus.webp",
    priceType: "all-in",
    driverWithFuelPrice: "Rp 1.400.000",
    year: 2023,
    fuel: "Diesel",
    rating: 4.8,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Isuzu Elf Minibus.",
    note: "Harga sudah termasuk mobil, supir & BBM.",
    passengers: 12,
    engine: "2800cc",
    transmission: "Manual",
    features: ["Spacious Cabin", "AC Double Blower"],
  },
  {
    id: "hiace-commuter-2023",
    name: "Toyota Hiace Commuter",
    category: "executive",
    image: "/images/cars/hiace-commuter.webp",
    priceType: "all-in",
    driverWithFuelPrice: "Rp 1.300.000",
    year: 2023,
    fuel: "Diesel",
    rating: 4.9,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Toyota Hiace Commuter.",
    note: "Harga sudah termasuk mobil, supir & BBM.",
    passengers: 15,
    engine: "2500cc",
    transmission: "Manual",
    features: ["Comfort Seats", "Audio System"],
  },
  {
    id: "hiace-premio-2023",
    name: "Toyota Hiace Premio",
    category: "executive",
    image: "/images/cars/hiace-premio.webp",
    priceType: "all-in",
    driverWithFuelPrice: "Rp 1.500.000",
    year: 2023,
    fuel: "Diesel",
    rating: 4.9,
    bookings: 82,
    whatsappText: "Halo, saya ingin menyewa Toyota Hiace Premio.",
    note: "Harga sudah termasuk mobil, supir & BBM.",
    passengers: 11,
    engine: "2800cc",
    transmission: "Manual",
    features: [
      "Spacious Cabin",
      "Reclining Seats",
      "USB Ports",
      "Individual AC Vents",
    ],
  },
  {
    id: "hiace-premio-luxury-2023",
    name: "Hiace Premio Luxury",
    category: "luxury",
    image: "/images/cars/hiace-premio-luxury.webp",
    priceType: "all-in",
    driverWithFuelPrice: "Rp 2.500.000",
    year: 2023,
    fuel: "Diesel",
    rating: 5.0,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Hiace Premio Luxury.",
    note: "Harga sudah termasuk mobil, supir & BBM.",
    passengers: 8,
    engine: "2800cc",
    transmission: "Manual",
    features: ["Luxury Interior", "Entertainment System"],
  },
  {
    id: "hilux-double-cabin-2023",
    name: "Toyota Hilux Double Cabin",
    category: "suv",
    image: "/images/cars/hilux-double-cabin.webp",
    priceType: "all-in",
    driverWithFuelPrice: "Rp 1.600.000",
    year: 2023,
    fuel: "Diesel",
    rating: 4.7,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Toyota Hilux Double Cabin.",
    note: "Harga sudah termasuk mobil, supir & BBM.",
    passengers: 5,
    engine: "2400cc",
    transmission: "Manual & Matic",
    features: ["4x4 System", "Cargo Space"],
  },
  {
    id: "alphard-new-2023",
    name: "Toyota Alphard New",
    category: "luxury",
    image: "/images/cars/alphard.webp",
    mobileImage: "/images/cars/Toyota-alphard-mobile.jpg", // Menambahkan gambar mobile
    priceType: "all-in",
    driverWithFuelPrice: "Rp 3.000.000",
    year: 2023,
    fuel: "Bensin",
    rating: 5.0,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Toyota Alphard New.",
    note: "Harga sudah termasuk mobil, supir & BBM.",
    passengers: 6,
    engine: "2500cc",
    transmission: "Matic",
    features: ["VIP Cabin", "Pilot Seats", "Entertainment System"],
  },
  {
    id: "innova-reborn-hybrid-2023",
    name: "Toyota Innova Zenix Hybrid",
    category: "mpv",
    image: "/images/cars/innova-reborn-hybrid.webp",
    mobileImage: "/images/cars/Toyota-innova-reborn-mobile.jpg",
    priceType: "lepas-kunci",
    manualPrice: "-",
    maticPrice: "Rp 750.000",
    driverWithFuelPrice: "Rp 1.100.000",
    year: 2023,
    fuel: "Hybrid",
    rating: 4.9,
    bookings: 0,
    whatsappText: "Halo, saya ingin menyewa Toyota Innova Zenix Hybrid.",
    passengers: 7,
    engine: "2000cc",
    transmission: "Matic",
    features: ["Smart Hybrid", "Panoramic Sunroof", "TSS"],
  },
];

export const getAllFleet = (): FleetCar[] => {
  return fleetData;
};

export const getFleetById = (id: string): FleetCar | undefined => {
  return fleetData.find((car) => car.id === id);
};

export const getFeaturedFleet = (count = 6): FleetCar[] => {
  return [...fleetData].sort((a, b) => b.bookings - a.bookings).slice(0, count);
};

export const getFleetByCategory = (category: string): FleetCar[] => {
  return fleetData.filter((car) => car.category === category);
};

// Fungsi baru untuk mendapatkan data hero slides
export const getHeroSlides = () => {
  const heroIds = [
    "avanza-2023-new",
    "innova-reborn-2023-new",
    "fortuner-2023",
    "alphard-new-2023",
  ];
  return heroIds
    .map((id) => {
      const car = getFleetById(id);
      return car
        ? {
            image: car.image,
            mobileImage: car.mobileImage,
            title: car.name,
            subtitle: car.note || car.name,
            price: car.maticPrice || car.driverWithFuelPrice || "",
            category: car.category.toUpperCase(),
          }
        : null;
    })
    .filter(Boolean); // Menghilangkan nilai null jika ada
};
