export type PriceType = "lepas-kunci" | "all-in" | "kontak";

export interface FleetCar {
  id: number;
  name: string;
  category: "city" | "mpv" | "suv" | "premium" | "luxury";
  image: string;
  priceType: PriceType;
  manualPrice?: string;
  maticPrice?: string;
  allInPrice?: string;
  note?: string;
  driverWithFuelPrice?: string;
  year: string;
  fuel: "Bensin" | "Diesel";
  whatsappText: string;
  available: boolean;
  bookings: number;
  rating: number;
  passengers?: number;
  engine?: string;
  transmission?: "Manual" | "Matic" | "Manual & Matic";
  features?: string[];
}

export const fleetData: FleetCar[] = [
  // --- Mobil Lepas Kunci (Manual & Matic) & Paket Supir ---
  {
    id: 1,
    name: "BRIO",
    category: "city",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Brio New 2023",
    available: true,
    bookings: 180,
    rating: 4.7,
    passengers: 5,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Sporty Design", "Touchscreen Audio", "Keyless Entry", "ABS"],
  },
  {
    id: 2,
    name: "AYLA",
    category: "city",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Ayla",
    available: true,
    bookings: 155,
    rating: 4.6,
    passengers: 5,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Compact Design", "Audio System"],
  },
  {
    id: 3,
    name: "AGYA",
    category: "city",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Agya",
    available: true,
    bookings: 162,
    rating: 4.6,
    passengers: 5,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Stylish Design", "Digital AC"],
  },
  {
    id: 4,
    name: "CALYA",
    category: "mpv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Calya",
    available: true,
    bookings: 190,
    rating: 4.5,
    passengers: 7,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Rear AC", "Spacious Cabin"],
  },
  {
    id: 5,
    name: "SIGRA",
    category: "mpv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 600.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Sigra",
    available: true,
    bookings: 210,
    rating: 4.5,
    passengers: 7,
    engine: "1200cc",
    transmission: "Manual & Matic",
    features: ["Dual SRS Airbags", "ISOFIX"],
  },
  {
    id: 6,
    name: "AVANZA / XENIA",
    category: "mpv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 300.000",
    maticPrice: "Rp 350.000",
    driverWithFuelPrice: "Rp 700.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Avanza/Xenia",
    available: true,
    bookings: 350,
    rating: 4.8,
    passengers: 7,
    engine: "1300cc",
    transmission: "Manual & Matic",
    features: ["Audio System", "Power Windows"],
  },
  {
    id: 7,
    name: "SUZUKI ERTIGA",
    category: "mpv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Suzuki Ertiga",
    available: true,
    bookings: 140,
    rating: 4.7,
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["Spacious Cabin", "Rear AC"],
  },
  {
    id: 8,
    name: "SUZUKI ERTIGA HYBRID",
    category: "mpv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Suzuki Ertiga Hybrid",
    available: true,
    bookings: 110,
    rating: 4.8,
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["Smart Hybrid", "Cruise Control"],
  },
  {
    id: 9,
    name: "MITSUBISHI XPANDER",
    category: "mpv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Mitsubishi Xpander",
    available: true,
    bookings: 220,
    rating: 4.8,
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: [
      "Cruise Control",
      "Spacious Cabin",
      "Rear AC",
      "Keyless Operation",
    ],
  },
  {
    id: 10,
    name: "SUZUKI XL7",
    category: "suv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Suzuki XL7",
    available: true,
    bookings: 135,
    rating: 4.7,
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["Sporty Design", "Hill Hold Control"],
  },
  {
    id: 11,
    name: "ALL NEW AVANZA",
    category: "mpv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan All New Avanza",
    available: true,
    bookings: 280,
    rating: 4.9,
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: [
      "Air Conditioner",
      "Audio System",
      "Power Windows",
      "Dual SRS Airbags",
    ],
  },
  {
    id: 12,
    name: "TERIOS",
    category: "suv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Terios",
    available: true,
    bookings: 175,
    rating: 4.6,
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["360 Camera", "Keyless Entry"],
  },
  {
    id: 13,
    name: "RUSH",
    category: "suv",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 700.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Rush",
    available: true,
    bookings: 198,
    rating: 4.7,
    passengers: 7,
    engine: "1500cc",
    transmission: "Manual & Matic",
    features: ["LED Headlights", "6 SRS Airbags"],
  },
  {
    id: 14,
    name: "GRAND INNOVA DIESEL",
    category: "premium",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 400.000",
    maticPrice: "Rp 450.000",
    driverWithFuelPrice: "Rp 900.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan Grand Innova Diesel",
    available: true,
    bookings: 250,
    rating: 4.8,
    passengers: 7,
    engine: "2500cc",
    transmission: "Manual & Matic",
    features: ["Diesel Engine", "Comfort Seats"],
  },
  {
    id: 15,
    name: "INNOVA REBORN",
    category: "premium",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    manualPrice: "Rp 550.000",
    maticPrice: "Rp 600.000",
    driverWithFuelPrice: "Rp 900.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan Innova Reborn",
    available: true,
    bookings: 410,
    rating: 4.9,
    passengers: 7,
    engine: "2400cc",
    transmission: "Manual & Matic",
    features: [
      "Captain Seats",
      "Premium Audio",
      "Climate Control",
      "ABS & EBD",
    ],
  },
  {
    id: 16,
    name: "INNOVA ZENIX",
    category: "premium",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "lepas-kunci",
    maticPrice: "Rp 750.000",
    driverWithFuelPrice: "Rp 1.000.000",
    note: "*Harga lepas kunci belum termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Innova Zenix",
    available: true,
    bookings: 215,
    rating: 5.0,
    passengers: 7,
    engine: "2000cc",
    transmission: "Matic",
    features: ["Captain Seats", "Sunroof", "TSS"],
  },

  // --- Mobil Hanya Paket All-In ---
  {
    id: 17,
    name: "TOYOTA FORTUNER",
    category: "premium",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "all-in",
    allInPrice: "Rp 1.300.000",
    driverWithFuelPrice: "Rp 1.500.000",
    note: "*Harga sudah termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan Toyota Fortuner",
    available: true,
    bookings: 188,
    rating: 4.9,
    passengers: 7,
    engine: "2800cc",
    transmission: "Matic",
    features: ["Leather Seats", "Sunroof", "360 Camera", "Advanced Safety"],
  },
  {
    id: 18,
    name: "MITSUBISHI PAJERO",
    category: "premium",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "all-in",
    allInPrice: "Rp 1.300.000",
    driverWithFuelPrice: "Rp 1.500.000",
    note: "*Harga sudah termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan Mitsubishi Pajero",
    available: true,
    bookings: 192,
    rating: 4.9,
    passengers: 7,
    engine: "2400cc",
    transmission: "Matic",
    features: [
      "Sunroof",
      "Cruise Control",
      "Leather Seats",
      "Hill Descent Control",
    ],
  },
  {
    id: 19,
    name: "ISUZU ELF MINIBUS",
    category: "luxury",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "all-in",
    allInPrice: "Rp 1.400.000",
    driverWithFuelPrice: "Rp 1.300.000",
    note: "*Harga sudah termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan Isuzu Elf Minibus",
    available: true,
    bookings: 95,
    rating: 4.8,
    passengers: 12,
    engine: "2800cc",
    transmission: "Manual",
    features: ["Spacious Cabin", "AC Double Blower"],
  },
  {
    id: 20,
    name: "HIACE COMMUTER",
    category: "luxury",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "all-in",
    allInPrice: "Rp 1.300.000",
    driverWithFuelPrice: "Rp 1.300.000",
    note: "*Harga sudah termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan HIACE",
    available: true,
    bookings: 120,
    rating: 4.8,
    passengers: 15,
    engine: "2500cc",
    transmission: "Manual",
    features: ["Comfort Seats", "Audio System"],
  },
  {
    id: 21,
    name: "HIACE PREMIO",
    category: "luxury",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "all-in",
    allInPrice: "Rp 1.500.000",
    driverWithFuelPrice: "Rp 1.500.000",
    note: "*Harga sudah termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan HIACE PREMIO",
    available: true,
    bookings: 145,
    rating: 4.9,
    passengers: 11,
    engine: "2800cc",
    transmission: "Manual",
    features: [
      "Spacious Cabin",
      "Reclining Seats",
      "USB Ports",
      "Individual AC Vents",
    ],
  },
  {
    id: 22,
    name: "HIACE PREMIO LUXURY",
    category: "luxury",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "all-in",
    allInPrice: "Rp 2.500.000",
    driverWithFuelPrice: "Rp 3.000.000",
    note: "*Harga sudah termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan HIACE PREMIO LUXURY",
    available: true,
    bookings: 80,
    rating: 5.0,
    passengers: 8,
    engine: "2800cc",
    transmission: "Manual",
    features: ["Luxury Interior", "Entertainment System"],
  },
  {
    id: 23,
    name: "HILUX DOUBLE CABIN",
    category: "premium",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "all-in",
    allInPrice: "Rp 1.600.000",
    driverWithFuelPrice: "Rp 1.600.000",
    note: "*Harga sudah termasuk driver & BBM",
    year: "2023",
    fuel: "Diesel",
    whatsappText: "Saya tertarik dengan HILUX DOUBLE CABIN",
    available: true,
    bookings: 70,
    rating: 4.8,
    passengers: 5,
    engine: "2400cc",
    transmission: "Manual & Matic",
    features: ["4x4 System", "Cargo Space"],
  },
  {
    id: 24,
    name: "TOYOTA ALPHARD",
    category: "luxury",
    image: "/placeholder.svg?width=400&height=300",
    priceType: "all-in",
    allInPrice: "Rp 2.400.000",
    driverWithFuelPrice: "Rp 2.500.000",
    note: "*Harga sudah termasuk driver & BBM",
    year: "2023",
    fuel: "Bensin",
    whatsappText: "Saya tertarik dengan Toyota Alphard",
    available: true,
    bookings: 99,
    rating: 5.0,
    passengers: 6,
    engine: "2500cc",
    transmission: "Matic",
    features: [
      "VIP Cabin",
      "Pilot Seats",
      "Entertainment System",
      "Sunroof & Moonroof",
    ],
  },
];

// Helper functions (Tetap sama seperti di file yang kamu kirimkan)
export function getFeaturedFleet(): FleetCar[] {
  return [...fleetData].sort((a, b) => b.bookings - a.bookings).slice(0, 6);
}

export function getAllFleet(): FleetCar[] {
  return [...fleetData];
}

export function getFleetByCategory(category: string): FleetCar[] {
  if (category === "all") {
    return [...fleetData];
  }
  return fleetData.filter((car) => car.category === category);
}

export function getFleetById(id: number): FleetCar | null {
  return fleetData.find((car) => car.id === id) || null;
}
